version: '3.8'

networks:
  rest:
  db:

volumes:
  mongodb-vol:


services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '127.0.0.1:27017:27017'
    volumes:
      - mongodb-vol:/data/db
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    networks:
      - db
    env_file:
      - mongo.env
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand({find:"vtv_news_db_prod.admin"}).ok' | mongosh --authenticationdatabase admin --host localhost -u root -p random_pass admin --quiet | grep -q 1
      interval: 10s
      timeout: 10s
      retries: 3 

  mongo-express:
    image: mongo-express
    container_name: mexpress
    #ports:
    #  - '8081:8081'
    networks:
      - db
    env_file:
      - express.env
    depends_on:
      mongodb:
        condition: service_healthy
      traefik:
        condition: service_started
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mongo-express.rule=Host(`express.bongda12h.net`)"
      - "traefik.http.routers.mongo-express.middlewares=transparent@file"
      - "traefik.http.services.mongo-express.loadbalancer.server.port=8081"

  traefik:
    image: traefik:2.5
    container_name: traefik
    restart: on-failure:5
    command:
      - "--log.level=DEBUG"
    environment:
      - TZ=${TIME_ZONE:-Europe/Berlin}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./proxy/config/:/etc/traefik/
    networks:
      - rest
      - db
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "2"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.bongda12h.net`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=web"
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth"
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/"

