[http.middlewares]
[http.middlewares.cors.headers]
accessControlAllowMethods = ["*"]
accessControlAllowHeaders= "*"
accessControlAllowOriginList = ["https://bongda12h.net"]
accessControlMaxAge = 3600
addVaryHeader = true
