[http.middlewares]
[http.middlewares.cors.headers]
accessControlAllowMethods = ["*"]
accessControlAllowHeaders= "*"
accessControlAllowOriginList = ["http://bongda12h.test"]
accessControlMaxAge = 3600
addVaryHeader = true
